version: "3.8"

services:
  pp5_form_submit:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}" # ใช้ PORT จาก .env ทั้ง host และ container
    env_file:
      - .env # Load environment variables from .env file
    # Optional: Add volumes for persistent data or hot-reloading during development
    # volumes:
    #   - .:/app
    #   - /app/node_modules
