version: "3.8"
services:
  web:
    build: .
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    # volumes:
    #   - .:/app
    restart: always
